version: '3'
services:
  cardserver:
    container_name: cardserver
    build:
      context: ./card_server/admin/
      dockerfile: Dockerfile
    image: cardserver:1.0.0
    env_file:
      - ./app.env
    volumes:
      - /home/webfile:/home/webfile
    ports:
      - "8880:8880"
      - "8888:8888"
    restart: always
